service: serverless-pdf-convert

frameworkVersion: '3'

plugins:
  - serverless-plugin-typescript
  - serverless-plugin-optimize
  - serverless-offline
  - serverless-stage-manager

custom:
  stages:
    - dev
    - test
    - acc
    - prod

provider:
  name: aws
  tracing:
    apiGateway: true
  runtime: nodejs12.x
  stage: ${opt:stage, 'dev'}
  region: us-east-1
  memorySize: 1536
  timeout: 20

package:
  patterns:
    - '!.gitignore'
    - '!README.md'
    - '!serverless.yml'
    - '!nest-cli.json'
    - '!.prettierrc'
  excludeDevDependencies: true
  individually: true

functions:
  main:
    handler: src/main.handler
    events:
      - http:
          method: any
          path: /{proxy+}
          cors: true
    layers:
      - arn:aws:lambda:us-east-1:764866452798:layer:libreoffice-brotli:1

